language: ruby
services:
  - postgresql
  - redis-server
env:
  secure: "HPj/T6XZntUgVv/FHRDMKNrLvyPgz6WL1Blm31h9zA6FusgYCCjzrQ0vlcygS2Gc7r6m18cbzh4sviJ9m1rmT7DlxFRYHDEBlTytJ+0Kr+43zO/i2Kheti2WUUtw3KyBehlf/FPGtNoBsvFqR3L3cBQM6zV/wFWrgyDS6ujzcc3rI/v0QaBPefd/rsgFj9fuXD8j+w+/FQSizRtqXXi7gPDrf/hc1rd936ZEzUYI33CVQqPLHdR6yXol8zdcta1RnRNHsIlVgH0khqG3k0UEAMSfyRGT7eS8yvOjG/8o6nI7n5R+7huietZaKogp4M66FyHGHkbDoOWVqM5/uGtQKRnWBjSLGeH7PORaUVhCQ5BPF0PTGRl0HzDmJ1Xy8waKhdbzpHZK4MKgu6TQWtoaFP5u/N2EQ7pGM6NFxrKEkH36CpqJeAitqPmZyHReOwgmKS1UCscAdisWkScuVSIlOrdBw+4CRE8UZaFdpFexvWVCeI0W+hmGfBfWqsWxkfeYbYxZ+Q9pv0PqUbEDWENhTUJmW5wUhJQd6904bXk9re7IoVCHaG1jAN0gIxo+K3SkX9+T5hlOGFYzwy/ddTN8xAnMLlvC5yQNs5a98BpNSx+rNJ/KHC2JGsYoc0FM4yEmmAzMZZUlY5Q7MBw9WdrwtrLtbwt2sT3MZIzApAywgvQ="
before_script:
  - psql -c 'create database mobile_data_scoring_app_test;' -U postgres
